source :rubygems
gem 'sinatra', '1.3.3'
gem 'slim',    '1.3.3'
gem 'json',    '1.7.5'
gem 'mysql2',  '0.3.11'
gem 'unicorn', '4.4.0'
gem 'memcache', '1.2.13'
gem 'sinatra-memcache', '0.1.1'

group :development do
  # run "bundle exec shotgun" on development
  gem 'shotgun'
end
